-- Existing single-seat licenses retain one seat. Ambiguous legacy assignments
-- require explicit reconciliation rather than inventing purchase quantities.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM assets a JOIN asset_license_details d USING(asset_id) WHERE a.assigned_to IS NOT NULL)
     OR EXISTS (SELECT 1 FROM asset_relationships WHERE relationship_type='INSTALLED_ON') THEN
    RAISE EXCEPTION 'Reconcile legacy license assignments before applying T11B allocations';
  END IF;
END $$;

ALTER TABLE asset_license_details ADD COLUMN seat_count INTEGER NOT NULL DEFAULT 1 CHECK (seat_count > 0);
CREATE TABLE license_allocations (
    allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_asset_id BIGINT NOT NULL REFERENCES asset_license_details(asset_id),
    device_asset_id BIGINT REFERENCES assets(asset_id),
    user_id BIGINT REFERENCES users(user_id),
    seat_count INTEGER NOT NULL CHECK (seat_count > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('RESERVED','ACTIVE','RELEASED')),
    handover_transaction_id BIGINT REFERENCES transactions(transaction_id),
    recovery_transaction_id BIGINT REFERENCES transactions(transaction_id),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMPTZ,
    CHECK ((status = 'RELEASED') = (released_at IS NOT NULL)),
    CHECK (device_asset_id IS NOT NULL OR user_id IS NOT NULL),
    CHECK (status <> 'ACTIVE' OR (user_id IS NOT NULL AND handover_transaction_id IS NOT NULL))
);
CREATE INDEX idx_license_allocations_package ON license_allocations(license_asset_id, status);
CREATE INDEX idx_license_allocations_user ON license_allocations(user_id, status);
CREATE UNIQUE INDEX uq_license_device_allocation ON license_allocations(license_asset_id, device_asset_id)
    WHERE status <> 'RELEASED' AND device_asset_id IS NOT NULL;
ALTER TABLE asset_relationships ADD COLUMN allocation_id BIGINT UNIQUE REFERENCES license_allocations(allocation_id);
ALTER TABLE asset_relationships ADD CONSTRAINT ck_relationship_allocation
    CHECK ((relationship_type = 'INSTALLED_ON') = (allocation_id IS NOT NULL));
CREATE UNIQUE INDEX uq_component_parent ON asset_relationships(child_asset_id) WHERE relationship_type='COMPONENT_OF';

-- All capacity writers serialize on the package row, including direct SQL.
CREATE FUNCTION validate_license_capacity() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE capacity INTEGER; used BIGINT;
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.license_asset_id <> OLD.license_asset_id THEN
        RAISE EXCEPTION 'Allocation package is immutable';
    END IF;
    SELECT seat_count INTO capacity FROM asset_license_details WHERE asset_id=NEW.license_asset_id FOR UPDATE;
    SELECT COALESCE(SUM(seat_count),0) INTO used FROM license_allocations
        WHERE license_asset_id=NEW.license_asset_id AND status <> 'RELEASED' AND allocation_id <> NEW.allocation_id;
    IF NEW.status <> 'RELEASED' AND used + NEW.seat_count > capacity THEN
        RAISE EXCEPTION 'License capacity exceeded';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_license_capacity BEFORE INSERT OR UPDATE ON license_allocations
    FOR EACH ROW EXECUTE FUNCTION validate_license_capacity();
CREATE FUNCTION validate_license_seat_reduction() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.seat_count < (SELECT COALESCE(SUM(seat_count),0) FROM license_allocations
                        WHERE license_asset_id=NEW.asset_id AND status <> 'RELEASED') THEN
        RAISE EXCEPTION 'License capacity below allocated seats';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_license_seat_reduction BEFORE UPDATE OF seat_count ON asset_license_details
    FOR EACH ROW EXECUTE FUNCTION validate_license_seat_reduction();
