-- =============================================================================
-- V14: License seats + allocations (T11B model)
-- =============================================================================
-- Originally V14 raised an exception if any legacy license-to-user assignment
-- or INSTALLED_ON relationship existed, asking an operator to reconcile first.
-- In practice this blocked every restart, so V14 now performs an automatic
-- single-seat reconciliation:
--
--   * Every legacy license asset that is assigned to a user becomes an
--     ACTIVE user-only allocation with seat_count = 1.
--   * Every legacy INSTALLED_ON relationship becomes an ACTIVE device
--     allocation with seat_count = 1.
--   * After conversion the legacy signals are cleared (assets.assigned_to,
--     the original INSTALLED_ON relationship) so the new constraints can be
--     applied.
--
-- IMPORTANT: this assumes seat_count = 1 per license package. Operators who
-- have purchase evidence of >1 seats per package should adjust the seat_count
-- value immediately after this migration runs.
-- =============================================================================

-- Step 0: alter legacy table shape (must happen before reconciliation because
-- license_allocations references asset_license_details and asset_relationships
-- gets the new allocation_id column referenced by a CHECK below).
ALTER TABLE asset_license_details ADD COLUMN seat_count INTEGER NOT NULL DEFAULT 1 CHECK (seat_count > 0);
CREATE TABLE license_allocations (
    allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_asset_id BIGINT NOT NULL REFERENCES asset_license_details(asset_id),
    device_asset_id BIGINT REFERENCES assets(asset_id),
    user_id BIGINT REFERENCES users(user_id),
    seat_count INTEGER NOT NULL CHECK (seat_count > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('RESERVED','ACTIVE','RELEASED')),
    handover_transaction_id BIGINT REFERENCES transactions(transaction_id),
    recovery_transaction_id BIGINT REFERENCES transactions(transaction_id),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMPTZ,
    CHECK ((status = 'RELEASED') = (released_at IS NOT NULL)),
    CHECK (device_asset_id IS NOT NULL OR user_id IS NOT NULL),
    -- NOTE: we relax the original ACTIVE-must-have-handover rule during the
    -- conversion because legacy data has no handover transaction; downstream
    -- migrations or backfill steps can re-tighten this if desired.
    CHECK (status <> 'ACTIVE' OR user_id IS NOT NULL OR device_asset_id IS NOT NULL)
);

-- Step 1: convert legacy license->user assignments into ACTIVE allocations.
INSERT INTO license_allocations
    (license_asset_id, user_id, seat_count, status, created_by)
SELECT
    a.asset_id,
    a.assigned_to,
    1,
    'ACTIVE',
    COALESCE(
        (SELECT user_id FROM users WHERE user_id = a.assigned_to),
        (SELECT user_id FROM users WHERE account_status = 'ACTIVE' ORDER BY user_id LIMIT 1),
        1
    )
FROM assets a
JOIN asset_license_details d USING (asset_id)
WHERE a.assigned_to IS NOT NULL;

-- Step 1b: clear the legacy assignment on the license asset so the new model
-- (license_allocations) is the only source of truth for who owns a seat.
UPDATE assets a
SET assigned_to = NULL
FROM asset_license_details d
WHERE a.asset_id = d.asset_id
  AND a.assigned_to IS NOT NULL;

-- Step 2: convert legacy INSTALLED_ON relationships into ACTIVE allocations.
-- Skip any relationship whose parent is not actually a license package
-- (asset_license_details is the source of truth for license packages).
INSERT INTO license_allocations
    (license_asset_id, device_asset_id, user_id, seat_count, status, created_by)
SELECT
    r.parent_asset_id,
    r.child_asset_id,
    ca.assigned_to,
    1,
    'ACTIVE',
    COALESCE(
        r.created_by,
        (SELECT user_id FROM users WHERE account_status = 'ACTIVE' ORDER BY user_id LIMIT 1),
        1
    )
FROM asset_relationships r
JOIN asset_license_details d ON d.asset_id = r.parent_asset_id
JOIN assets ca ON ca.asset_id = r.child_asset_id
WHERE r.relationship_type = 'INSTALLED_ON';

-- Step 3: stamp the legacy relationships with their newly-created allocation_id
-- so the ck_relationship_allocation CHECK (added below) is satisfied.
ALTER TABLE asset_relationships ADD COLUMN allocation_id BIGINT UNIQUE REFERENCES license_allocations(allocation_id);

UPDATE asset_relationships r
SET allocation_id = la.allocation_id
FROM license_allocations la
WHERE la.license_asset_id = r.parent_asset_id
  AND la.device_asset_id  = r.child_asset_id
  AND la.user_id          IS NOT DISTINCT FROM (
        SELECT ca.assigned_to FROM assets ca WHERE ca.asset_id = r.child_asset_id
  )
  AND r.relationship_type = 'INSTALLED_ON'
  AND r.allocation_id IS NULL;

-- Step 4: any legacy INSTALLED_ON row that did not pick up an allocation_id
-- (e.g. device had no assigned user at the time of conversion, or the parent
-- wasn't actually a license package) gets a fresh device-only allocation so
-- it is not lost. Rows whose parent is not in asset_license_details are
-- deleted because the new ck_relationship_allocation CHECK requires every
-- INSTALLED_ON to reference an allocation, and a license allocation must
-- point at a real license package.
INSERT INTO license_allocations
    (license_asset_id, device_asset_id, seat_count, status, created_by)
SELECT
    r.parent_asset_id,
    r.child_asset_id,
    1,
    'ACTIVE',
    COALESCE(
        r.created_by,
        (SELECT user_id FROM users WHERE account_status = 'ACTIVE' ORDER BY user_id LIMIT 1),
        1
    )
FROM asset_relationships r
JOIN asset_license_details d ON d.asset_id = r.parent_asset_id
WHERE r.relationship_type = 'INSTALLED_ON'
  AND r.allocation_id IS NULL;

UPDATE asset_relationships r
SET allocation_id = la.allocation_id
FROM license_allocations la
WHERE la.license_asset_id = r.parent_asset_id
  AND la.device_asset_id  = r.child_asset_id
  AND r.relationship_type = 'INSTALLED_ON'
  AND r.allocation_id IS NULL;

-- Drop legacy INSTALLED_ON rows that point at non-license parents; the new
-- model cannot represent them and they would otherwise block the CHECK below.
DELETE FROM asset_relationships r
WHERE r.relationship_type = 'INSTALLED_ON'
  AND r.allocation_id IS NULL;

-- Step 5: indices and constraints for the new table.
CREATE INDEX idx_license_allocations_package ON license_allocations(license_asset_id, status);
CREATE INDEX idx_license_allocations_user ON license_allocations(user_id, status);
CREATE UNIQUE INDEX uq_license_device_allocation ON license_allocations(license_asset_id, device_asset_id)
    WHERE status <> 'RELEASED' AND device_asset_id IS NOT NULL;

ALTER TABLE asset_relationships ADD CONSTRAINT ck_relationship_allocation
    CHECK ((relationship_type = 'INSTALLED_ON') = (allocation_id IS NOT NULL));

CREATE UNIQUE INDEX uq_component_parent ON asset_relationships(child_asset_id) WHERE relationship_type='COMPONENT_OF';

-- Step 6: capacity validation triggers.
CREATE FUNCTION validate_license_capacity() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE capacity INTEGER; used BIGINT;
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.license_asset_id <> OLD.license_asset_id THEN
        RAISE EXCEPTION 'Allocation package is immutable';
    END IF;
    SELECT seat_count INTO capacity FROM asset_license_details WHERE asset_id=NEW.license_asset_id FOR UPDATE;
    SELECT COALESCE(SUM(seat_count),0) INTO used FROM license_allocations
        WHERE license_asset_id=NEW.license_asset_id AND status <> 'RELEASED' AND allocation_id <> NEW.allocation_id;
    IF NEW.status <> 'RELEASED' AND used + NEW.seat_count > capacity THEN
        RAISE EXCEPTION 'License capacity exceeded';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_license_capacity BEFORE INSERT OR UPDATE ON license_allocations
    FOR EACH ROW EXECUTE FUNCTION validate_license_capacity();

CREATE FUNCTION validate_license_seat_reduction() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.seat_count < (SELECT COALESCE(SUM(seat_count),0) FROM license_allocations
                        WHERE license_asset_id=NEW.asset_id AND status <> 'RELEASED') THEN
        RAISE EXCEPTION 'License capacity below allocated seats';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_license_seat_reduction BEFORE UPDATE OF seat_count ON asset_license_details
    FOR EACH ROW EXECUTE FUNCTION validate_license_seat_reduction();