-- Durable integration events: consumers in T17 only see committed workflow changes.
CREATE TABLE receiving_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id bigint NOT NULL REFERENCES transactions(transaction_id),
    revision integer NOT NULL,
    event_type varchar(30) NOT NULL CHECK (event_type IN ('SUBMITTED','WITHDRAWN','COMPLETED','REJECTED')),
    actor_id bigint NOT NULL REFERENCES users(user_id),
    occurred_at timestamptz NOT NULL DEFAULT now(),
    reason text,
    UNIQUE(transaction_id, revision, event_type)
);
CREATE INDEX receiving_events_pending ON receiving_events(event_id);
