CREATE TABLE publication_attempts (
    publication_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transactions(transaction_id),
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('PDF')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('FAILED')),
    error_message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_publication_attempts_transaction_created
    ON publication_attempts(transaction_id, created_at DESC);
