-- Align the original prototype schema with the approved ITAM domain model.
-- This migration deliberately preserves source tables/columns where legacy rows
-- cannot be classified with certainty; V7 removes only data that is verifiably migrated.

-- Identity and master data
UPDATE roles SET code = 'IT_STAFF' WHERE code = 'IT';
UPDATE roles SET code = 'PUR_STAFF' WHERE code = 'PUR';
ALTER TABLE users ADD COLUMN account_status VARCHAR(20);
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255);
UPDATE users SET account_status = CASE WHEN is_active THEN 'ACTIVE' ELSE 'LOCKED' END;
ALTER TABLE users ALTER COLUMN account_status SET DEFAULT 'ACTIVE';
ALTER TABLE users ALTER COLUMN account_status SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT chk_users_account_status
    CHECK (account_status IN ('ACTIVE', 'LOCKED'));

UPDATE asset_categories SET code = 'DEVICE', name = 'Device' WHERE code = 'HARDWARE';
UPDATE asset_categories SET code = 'LICENSE', name = 'License' WHERE code = 'SOFTWARE';
UPDATE asset_categories SET code = 'COMPONENT', name = 'Component', is_active = FALSE
WHERE code = 'CONSUMABLE';
ALTER TABLE asset_types RENAME COLUMN type_name TO name;
ALTER TABLE asset_types ADD COLUMN category_id BIGINT;
INSERT INTO asset_types (code, name, category_id, is_active)
SELECT v.code, v.name, c.category_id, TRUE
FROM (VALUES
    ('LAPTOP', 'Laptop', 'DEVICE'),
    ('DESKTOP', 'Desktop', 'DEVICE'),
    ('MONITOR', 'Monitor', 'DEVICE'),
    ('SERVER', 'Server', 'DEVICE'),
    ('PRINTER', 'Printer', 'DEVICE'),
    ('RAM', 'RAM', 'COMPONENT'),
    ('STORAGE', 'Storage', 'COMPONENT'),
    ('SOFTWARE_LICENSE', 'Software License', 'LICENSE')
) AS v(code, name, category_code)
JOIN asset_categories c ON c.code = v.category_code
ON CONFLICT (code) DO UPDATE SET category_id = EXCLUDED.category_id;

-- Safe transitional types retain legacy rows without guessing a precise model.
INSERT INTO asset_types (code, name, category_id, is_active)
SELECT 'LEGACY_' || c.code, 'Legacy ' || c.name, c.category_id, FALSE
FROM asset_categories c
WHERE EXISTS (SELECT 1 FROM assets a WHERE a.category_id = c.category_id)
ON CONFLICT (code) DO NOTHING;

UPDATE asset_types t
SET category_id = c.category_id
FROM asset_categories c
WHERE t.category_id IS NULL
  AND (t.code = 'SOFTWARE_LICENSE' AND c.code = 'LICENSE'
       OR t.code IN ('RAM', 'STORAGE') AND c.code = 'COMPONENT'
       OR t.code NOT IN ('SOFTWARE_LICENSE', 'RAM', 'STORAGE') AND c.code = 'DEVICE');
ALTER TABLE asset_types ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE asset_types ADD CONSTRAINT fk_asset_types_category
    FOREIGN KEY (category_id) REFERENCES asset_categories(category_id) ON DELETE RESTRICT;

ALTER TABLE models ALTER COLUMN brand SET NOT NULL;
ALTER TABLE models ADD CONSTRAINT uq_models_type_brand_name UNIQUE (type_id, brand, name);

ALTER TABLE software_catalog ALTER COLUMN manufacturer SET NOT NULL;
ALTER TABLE software_catalog ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE software_catalog ADD COLUMN updated_at TIMESTAMPTZ;
CREATE UNIQUE INDEX uq_software_catalog_identity
    ON software_catalog (manufacturer, name, COALESCE(version, ''));

CREATE TABLE license_assignment_types (
    license_assignment_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_license_assignment_types_code_not_blank CHECK (BTRIM(code) <> '')
);
CREATE TABLE license_term_types (
    license_term_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_license_term_types_code_not_blank CHECK (BTRIM(code) <> '')
);
INSERT INTO license_assignment_types (code, name) VALUES ('OEM', 'OEM'), ('PER_USER', 'Per User');
INSERT INTO license_term_types (code, name) VALUES ('PERPETUAL', 'Perpetual'), ('SUBSCRIPTION', 'Subscription');

-- Assets
ALTER TABLE assets ADD COLUMN type_id BIGINT;
UPDATE assets a SET type_id = t.type_id
FROM asset_categories c
JOIN asset_types t ON t.code = 'LEGACY_' || c.code
WHERE a.category_id = c.category_id;
ALTER TABLE assets ALTER COLUMN type_id SET NOT NULL;
ALTER TABLE assets ADD CONSTRAINT fk_assets_type
    FOREIGN KEY (type_id) REFERENCES asset_types(type_id) ON DELETE RESTRICT;
CREATE INDEX idx_assets_type ON assets(type_id);
CREATE INDEX idx_assets_supplier ON assets(supplier_id);
CREATE INDEX idx_assets_purchase_date ON assets(purchase_date);

ALTER TABLE asset_hardware_details ALTER COLUMN serial_number DROP NOT NULL;
CREATE INDEX idx_asset_hardware_warranty ON asset_hardware_details(warranty_expiration);

ALTER TABLE asset_software_details RENAME TO asset_license_details;
ALTER TABLE asset_license_details ADD COLUMN license_assignment_type_id BIGINT;
ALTER TABLE asset_license_details ADD COLUMN license_term_type_id BIGINT;
UPDATE asset_license_details d SET license_assignment_type_id = a.license_assignment_type_id
FROM software_license_types old_type
JOIN license_assignment_types a ON a.code = old_type.code
WHERE d.license_type_id = old_type.license_type_id AND old_type.code IN ('OEM', 'PER_USER');
UPDATE asset_license_details d SET license_term_type_id = t.license_term_type_id
FROM software_license_types old_type
JOIN license_term_types t ON t.code = old_type.code
WHERE d.license_type_id = old_type.license_type_id AND old_type.code = 'PERPETUAL';
UPDATE asset_license_details
SET license_assignment_type_id = (SELECT license_assignment_type_id FROM license_assignment_types WHERE code = 'PER_USER')
WHERE license_assignment_type_id IS NULL;
UPDATE asset_license_details
SET license_term_type_id = (SELECT license_term_type_id FROM license_term_types WHERE code = 'PERPETUAL')
WHERE license_term_type_id IS NULL;
ALTER TABLE asset_license_details ALTER COLUMN license_assignment_type_id SET NOT NULL;
ALTER TABLE asset_license_details ALTER COLUMN license_term_type_id SET NOT NULL;
ALTER TABLE asset_license_details ADD CONSTRAINT fk_asset_license_assignment_type
    FOREIGN KEY (license_assignment_type_id) REFERENCES license_assignment_types(license_assignment_type_id) ON DELETE RESTRICT;
ALTER TABLE asset_license_details ADD CONSTRAINT fk_asset_license_term_type
    FOREIGN KEY (license_term_type_id) REFERENCES license_term_types(license_term_type_id) ON DELETE RESTRICT;
CREATE INDEX idx_asset_license_expiry ON asset_license_details(expiry_date);

CREATE OR REPLACE FUNCTION fn_validate_asset_license_expiry()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_term_code VARCHAR(50);
BEGIN
  SELECT code INTO v_term_code FROM license_term_types
  WHERE license_term_type_id = NEW.license_term_type_id;
  IF v_term_code = 'SUBSCRIPTION' AND NEW.expiry_date IS NULL THEN
    RAISE EXCEPTION 'SUBSCRIPTION license must have expiry_date';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_validate_asset_license_expiry
BEFORE INSERT OR UPDATE OF license_term_type_id, expiry_date
ON asset_license_details FOR EACH ROW
EXECUTE FUNCTION fn_validate_asset_license_expiry();

ALTER TABLE asset_relationships ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE asset_relationships ADD CONSTRAINT chk_asset_relationship_type
    CHECK (relationship_type IN ('COMPONENT_OF', 'INSTALLED_ON'));

-- Transactions and type-specific details
ALTER TABLE transactions ADD COLUMN updated_at TIMESTAMPTZ;
UPDATE transactions SET status = 'COMPLETED' WHERE status IN ('APPROVED', 'DONE');
ALTER TABLE transactions ADD CONSTRAINT chk_transaction_type
    CHECK (type IN ('IMPORT', 'HANDOVER', 'RECOVERY', 'DISPOSAL'));
ALTER TABLE transactions ADD CONSTRAINT chk_transaction_status
    CHECK (status IN ('PENDING', 'COMPLETED', 'REJECTED'));
ALTER TABLE transactions ADD CONSTRAINT chk_transaction_state
    CHECK (
      (status = 'PENDING' AND processed_by IS NULL AND processed_at IS NULL
       AND completed_at IS NULL AND rejection_reason IS NULL)
      OR (status = 'COMPLETED' AND processed_by IS NOT NULL AND processed_at IS NOT NULL
          AND completed_at IS NOT NULL AND rejection_reason IS NULL)
      OR (status = 'REJECTED' AND processed_by IS NOT NULL AND processed_at IS NOT NULL
          AND completed_at IS NULL AND NULLIF(BTRIM(rejection_reason), '') IS NOT NULL)
    );
CREATE INDEX idx_transactions_processed ON transactions(processed_by, processed_at);

CREATE TABLE transaction_import_details (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(supplier_id) ON DELETE RESTRICT,
    po_number VARCHAR(100) NOT NULL,
    import_date DATE NOT NULL,
    receiving_location_id BIGINT NOT NULL REFERENCES locations(location_id) ON DELETE RESTRICT
);
CREATE TABLE transaction_handover_details (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    recipient_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    handover_date DATE NOT NULL,
    destination_location_id BIGINT NOT NULL REFERENCES locations(location_id) ON DELETE RESTRICT
);
CREATE TABLE transaction_recovery_details (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    returner_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    recovery_date DATE NOT NULL,
    receiving_location_id BIGINT NOT NULL REFERENCES locations(location_id) ON DELETE RESTRICT,
    reason TEXT NOT NULL CHECK (NULLIF(BTRIM(reason), '') IS NOT NULL)
);
CREATE TABLE transaction_disposal_details (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    reason TEXT NOT NULL CHECK (NULLIF(BTRIM(reason), '') IS NOT NULL),
    disposal_date DATE
);

ALTER TABLE transaction_assets ADD COLUMN line_number INTEGER;
WITH numbered AS (
  SELECT transaction_asset_id,
         ROW_NUMBER() OVER (PARTITION BY transaction_id ORDER BY transaction_asset_id) AS rn
  FROM transaction_assets
)
UPDATE transaction_assets ta SET line_number = numbered.rn FROM numbered
WHERE ta.transaction_asset_id = numbered.transaction_asset_id;
ALTER TABLE transaction_assets ALTER COLUMN line_number SET NOT NULL;
ALTER TABLE transaction_assets ADD CONSTRAINT chk_transaction_asset_line CHECK (line_number > 0);
ALTER TABLE transaction_assets ADD CONSTRAINT uq_transaction_asset_line UNIQUE (transaction_id, line_number);
CREATE UNIQUE INDEX uq_transaction_asset_asset
    ON transaction_assets(transaction_id, asset_id) WHERE asset_id IS NOT NULL;

-- Documents, audit, imports, and sandbox email
ALTER TABLE documents ADD COLUMN is_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE documents ADD CONSTRAINT uq_documents_stored_file UNIQUE (stored_file_name);

CREATE TABLE audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    transaction_id BIGINT REFERENCES transactions(transaction_id) ON DELETE RESTRICT,
    actor_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    action VARCHAR(50) NOT NULL,
    old_data JSONB,
    new_data JSONB,
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_audit_entity_type CHECK
      (entity_type IN ('ASSET', 'TRANSACTION', 'USER', 'DOCUMENT', 'MASTER_DATA', 'IMPORT_BATCH'))
);
INSERT INTO audit_logs
    (entity_type, entity_id, transaction_id, actor_user_id, action, old_data, new_data, details, created_at)
SELECT 'ASSET', asset_id, transaction_id, actor_user_id, action, old_data, new_data, details, created_at
FROM asset_history;
CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id, created_at);
CREATE INDEX idx_audit_transaction ON audit_logs(transaction_id, created_at);
CREATE INDEX idx_audit_actor ON audit_logs(actor_user_id, created_at);

ALTER TABLE import_batches ADD COLUMN duplicate_rows INTEGER NOT NULL DEFAULT 0;
ALTER TABLE import_batches ADD CONSTRAINT chk_import_batch_counts
    CHECK (total_rows >= 0 AND valid_rows >= 0 AND invalid_rows >= 0
           AND duplicate_rows >= 0 AND imported_rows >= 0);
ALTER TABLE import_batches ADD CONSTRAINT chk_import_batch_status
    CHECK (status IN ('UPLOADED', 'VALIDATED', 'IMPORTING', 'COMPLETED', 'FAILED'));
ALTER TABLE import_rows ADD CONSTRAINT chk_import_row_number CHECK (row_number > 0);
ALTER TABLE import_rows ADD CONSTRAINT chk_import_row_status
    CHECK (validation_status IN ('VALID', 'INVALID', 'DUPLICATE', 'IMPORTED'));
ALTER TABLE import_rows ADD CONSTRAINT chk_import_row_error
    CHECK (validation_status NOT IN ('INVALID', 'DUPLICATE')
           OR NULLIF(BTRIM(error_message), '') IS NOT NULL);
ALTER TABLE email_logs ADD CONSTRAINT chk_email_status
    CHECK (status IN ('PENDING', 'SENT', 'FAILED'));
ALTER TABLE email_logs ADD CONSTRAINT chk_email_state
    CHECK ((status <> 'SENT' OR sent_at IS NOT NULL)
       AND (status <> 'FAILED' OR NULLIF(BTRIM(error_message), '') IS NOT NULL));
CREATE INDEX idx_email_transaction_status ON email_logs(transaction_id, status);

CREATE UNIQUE INDEX uq_supplier_contact_email
    ON supplier_contacts(supplier_id, email) WHERE email IS NOT NULL;
