spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itam_test
    username: itam_test
    password: change_me

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  flyway:
    enabled: false

logging:
  level:
    root: WARN
